application: yangpei
version: 1
runtime: python27
threadsafe: yes
api_version: 1

default_expiration: "7d"

handlers:
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
  
- url: /static/
  static_dir: static

- url: /admin/.*
  script: blog.application
  login: required

- url: /.*
  script: blog.application